import { http, HttpResponse } from 'msw'
import type { Category, MovementType } from '@/features/categories/schemas'
import { API_URL } from '@/lib/api'
import { db, nextId, nowIso, saveDb } from '../db'
import { invalidData, notFound, parseId, resolveOrganization, type FieldDetail } from './context'

// "Cobro de facturas" is required by docs/03 (movements generated by payments use it).
// The rest are a proposal, pending confirmation in docs/08-contrato-api.md.
const DEFAULT_CATEGORIES: { name: string; type: MovementType }[] = [
  { name: 'Cobro de facturas', type: 'INCOME' },
  { name: 'Ventas', type: 'INCOME' },
  { name: 'Otros ingresos', type: 'INCOME' },
  { name: 'Alquiler', type: 'EXPENSE' },
  { name: 'Servicios contratados', type: 'EXPENSE' },
  { name: 'Impuestos', type: 'EXPENSE' },
  { name: 'Otros egresos', type: 'EXPENSE' },
]

/** Called when an organization is created, like the backend is expected to do. */
export function seedDefaultCategories(organizationId: number): void {
  const now = nowIso()
  for (const category of DEFAULT_CATEGORIES) {
    db.categories.push({
      id: nextId(),
      organizationId,
      ...category,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    })
  }
}

type CategoryBody = Partial<Pick<Category, 'name' | 'type' | 'isActive'>>

function validate(body: CategoryBody, partial: boolean): FieldDetail[] {
  const details: FieldDetail[] = []
  if ((!partial || body.name !== undefined) && !body.name?.trim()) {
    details.push({ field: 'name', message: 'Required' })
  }
  if (!partial && body.type !== 'INCOME' && body.type !== 'EXPENSE') {
    details.push({ field: 'type', message: 'Invalid type' })
  }
  if (partial && body.type !== undefined) {
    details.push({ field: 'type', message: 'Type cannot be changed' })
  }
  return details
}

function duplicatedName(
  organizationId: number,
  name: string,
  type: MovementType,
  exceptId?: number,
) {
  return db.categories.some(
    (category) =>
      category.organizationId === organizationId &&
      category.type === type &&
      category.name.toLowerCase() === name.trim().toLowerCase() &&
      category.id !== exceptId,
  )
}

export const categoryHandlers = [
  http.get(`${API_URL}/api/categories`, ({ request }) => {
    const organization = resolveOrganization(request)
    if (organization instanceof Response) return organization
    const params = new URL(request.url).searchParams
    const type = params.get('type')
    const includeInactive = params.get('includeInactive') === 'true'
    const categories = db.categories
      .filter((category) => category.organizationId === organization.id)
      .filter((category) => !type || category.type === type)
      .filter((category) => includeInactive || category.isActive)
      .sort((a, b) => a.name.localeCompare(b.name, 'es'))
    return HttpResponse.json(categories)
  }),

  http.post(`${API_URL}/api/categories`, async ({ request }) => {
    const organization = resolveOrganization(request)
    if (organization instanceof Response) return organization
    const body = (await request.json()) as CategoryBody
    const details = validate(body, false)
    if (details.length) return invalidData(details)
    const type = body.type as MovementType
    const name = body.name?.trim() ?? ''
    if (duplicatedName(organization.id, name, type)) {
      return HttpResponse.json({ error: 'Category already exists' }, { status: 409 })
    }
    const now = nowIso()
    const category: Category = {
      id: nextId(),
      organizationId: organization.id,
      name,
      type,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    }
    db.categories.push(category)
    saveDb()
    return HttpResponse.json(category, { status: 201 })
  }),

  http.patch(`${API_URL}/api/categories/:id`, async ({ request, params }) => {
    const organization = resolveOrganization(request)
    if (organization instanceof Response) return organization
    const category = db.categories.find(
      (candidate) =>
        candidate.id === parseId(params.id) && candidate.organizationId === organization.id,
    )
    if (!category) return notFound('Category')
    const body = (await request.json()) as CategoryBody
    const details = validate(body, true)
    if (details.length) return invalidData(details)
    if (
      body.name !== undefined &&
      duplicatedName(organization.id, body.name, category.type, category.id)
    ) {
      return HttpResponse.json({ error: 'Category already exists' }, { status: 409 })
    }
    Object.assign(category, body, body.name ? { name: body.name.trim() } : {}, {
      updatedAt: nowIso(),
    })
    saveDb()
    return HttpResponse.json(category)
  }),
]
