CREATE TYPE "activity_kind" AS ENUM (
  'GOODS',
  'SERVICES'
);

CREATE TYPE "category_type" AS ENUM (
  'INCOME',
  'EXPENSE'
);

CREATE TYPE "transaction_type" AS ENUM (
  'INCOME',
  'EXPENSE'
);

CREATE TYPE "invoice_concept" AS ENUM (
  'GOODS',
  'SERVICES',
  'GOODS_AND_SERVICES'
);

CREATE TYPE "invoice_status" AS ENUM (
  'DRAFT',
  'PENDING',
  'AUTHORIZED',
  'REJECTED'
);

CREATE TYPE "voucher_type" AS ENUM (
  'FACTURA_C'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "organizations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "cuit" varchar(11) UNIQUE NOT NULL,
  "legal_name" varchar(255) NOT NULL,
  "trade_name" varchar(255),
  "commercial_address" varchar(255),
  "tax_condition" varchar(50) NOT NULL,
  "monotributo_category" varchar(10),
  "activity_start_date" date,
  "gross_income_number" varchar(50),
  "base_currency" varchar(3) NOT NULL DEFAULT 'ARS',
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "activities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "arca_activity_code" varchar(20),
  "description" varchar(255) NOT NULL,
  "activity_kind" activity_kind NOT NULL,
  "is_primary" boolean NOT NULL DEFAULT false,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "points_of_sale" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "number" int NOT NULL,
  "billing_method" varchar(50) NOT NULL DEFAULT 'ELECTRONIC',
  "address" varchar(255),
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "doc_type" varchar(20),
  "doc_number" varchar(20),
  "name" varchar(255) NOT NULL,
  "address" varchar(255),
  "tax_condition" varchar(50),
  "email" varchar(255),
  "phone" varchar(50),
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "name" varchar(100) NOT NULL,
  "type" category_type NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "exchange_rates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "source" varchar(50) NOT NULL,
  "rate_type" varchar(50) NOT NULL,
  "from_currency" varchar(3) NOT NULL,
  "to_currency" varchar(3) NOT NULL,
  "value" decimal(18,6) NOT NULL,
  "observed_at" timestamp NOT NULL
);

CREATE TABLE "invoices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "point_of_sale_id" int NOT NULL,
  "client_id" int,
  "voucher_type" voucher_type NOT NULL DEFAULT 'FACTURA_C',
  "voucher_number" int,
  "concept" invoice_concept NOT NULL,
  "issue_date" date NOT NULL,
  "recipient_doc_type" varchar(20),
  "recipient_doc_number" varchar(20),
  "recipient_name" varchar(255),
  "recipient_address" varchar(255),
  "recipient_tax_condition" varchar(50),
  "currency" varchar(3) NOT NULL DEFAULT 'ARS',
  "fiscal_exchange_rate" decimal(18,6) NOT NULL DEFAULT 1,
  "service_from" date,
  "service_to" date,
  "payment_due_date" date,
  "total_amount" decimal(18,2) NOT NULL,
  "status" invoice_status NOT NULL DEFAULT 'DRAFT',
  "cae" varchar(50),
  "cae_expiration" date,
  "created_at" timestamp NOT NULL,
  "authorized_at" timestamp
);

CREATE TABLE "invoice_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" int NOT NULL,
  "description" varchar(255) NOT NULL,
  "quantity" decimal(18,3) NOT NULL,
  "unit_price" decimal(18,2) NOT NULL,
  "subtotal" decimal(18,2) NOT NULL
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" int NOT NULL,
  "amount" decimal(18,2) NOT NULL,
  "payment_date" date NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" int NOT NULL,
  "payment_id" int UNIQUE,
  "category_id" int,
  "type" transaction_type NOT NULL,
  "amount" decimal(18,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'ARS',
  "exchange_rate" decimal(18,6),
  "transaction_date" date NOT NULL,
  "description" varchar(255),
  "created_at" timestamp NOT NULL
);

CREATE UNIQUE INDEX ON "points_of_sale" ("organization_id", "number");

CREATE UNIQUE INDEX ON "invoices" ("point_of_sale_id", "voucher_type", "voucher_number");

ALTER TABLE "organizations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activities" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "points_of_sale" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "clients" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exchange_rates" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("point_of_sale_id") REFERENCES "points_of_sale" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoice_items" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;
